### ISSUE TITLE
Password not being import, despite being in the csv for import

### ISSUE THREAD

**Issue by mattboddie** [EyeSeeTea/user-extended-app-blessed#39]
Hi there! Love the App! Just started using it.

I have noticed that the Password doesn't seem to get imported into the interface with the csv upload.  Attaching a small gif and accompanying csv (pasted below) that we used.

Environment: Google Chrome
DHIS-2 Version: 2.35.1

Username | Password | Name | firstName | Surname | Email | Updated | Last   login | Created | Roles | userGroups | organisationUnits | dataViewOrganisationUnits
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Upload_Test | P@ssword1 | Upload_Test | Upload | Test |   |   |   |   |   | Spray Group (Pro-Cat)\|\|Mobilizer Group (Pro-Cat) | Benin\|\|Burkina Faso | PMI VectorLink
![Adding 1 User to Test](https://user-images.githubusercontent.com/45822435/102501634-a6cb5380-404b-11eb-9ed4-076867c9802e.gif)

**Comment by adrianq** [comment]
Hi @mattboddie 
Thanks for providing feedback! Glad that you like the app!

We will review this feature for the next version of the app that will be released in a couple of features. However, keep in mind user-extended-app isn't supported for DHIS2 2.35. The latest version we support is DHIS2 2.34 and we have no plans to support 2.35 for now. The application is open-source and it has been funded by different organizations and occasional efforts on our side. If you would like us to provide support for this version or any other change, feel free to contact us at hello@eyeseetea.com and we can discuss the specifics.

**Comment by adrianq** [comment]
@mattboddie we have tested the import feature and it seems to be working fine in the supported versions of DHIS2. I also quickly tested in 2.35 and it looks like the password is showing in the interface and the user gets imported. Disclaimer: as I said before, the app is not fully supported for DHIS2 2.35 and we haven't done extensive tests so they may be some bugs (in particular because there are relevant changes in DHIS2 user API for this version).

This is the content of the file we use taking yours as a reference:
```
Username,Password,Name,firstName,Surname,Email,Updated,Last login,Created,Roles,userGroups,organisationUnits,dataViewOrganisationUnits
Upload_Test,P@ssword1,Upload_Test,Upload,Test,   ,   ,   ,   ,   ,Spray Group (Pro-Cat)||Mobilizer Group (Pro-Cat),Benin||Burkina Faso,PMI VectorLink
```

This is the pre-import interface:
![image](https://user-images.githubusercontent.com/6850223/107050087-c0bf2200-67c2-11eb-96a4-59064356dbb7.png)

**Comment by adrianq** [comment]
@mattboddie Just a final comment, the application has now been tested on DHIS2 2.35. We have implemented a few minor changes to make it compatible with this version. These changes can be found in the latest release (https://github.com/EyeSeeTea/user-extended-app-blessed/releases/tag/v0.6.0) in case you want to give it a try. Cheers!
